// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: currency/currency_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRateByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateByDateRequest) Reset() {
	*x = GetRateByDateRequest{}
	mi := &file_currency_currency_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateByDateRequest) ProtoMessage() {}

func (x *GetRateByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateByDateRequest.ProtoReflect.Descriptor instead.
func (*GetRateByDateRequest) Descriptor() ([]byte, []int) {
	return file_currency_currency_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRateByDateRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type GetRateByDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Rub           map[string]float64     `protobuf:"bytes,2,rep,name=rub,proto3" json:"rub,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateByDateResponse) Reset() {
	*x = GetRateByDateResponse{}
	mi := &file_currency_currency_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateByDateResponse) ProtoMessage() {}

func (x *GetRateByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateByDateResponse.ProtoReflect.Descriptor instead.
func (*GetRateByDateResponse) Descriptor() ([]byte, []int) {
	return file_currency_currency_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRateByDateResponse) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *GetRateByDateResponse) GetRub() map[string]float64 {
	if x != nil {
		return x.Rub
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_currency_currency_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_currency_currency_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetHistoryRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetHistoryRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type DateRates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Rub           map[string]float64     `protobuf:"bytes,2,rep,name=rub,proto3" json:"rub,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRates) Reset() {
	*x = DateRates{}
	mi := &file_currency_currency_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRates) ProtoMessage() {}

func (x *DateRates) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRates.ProtoReflect.Descriptor instead.
func (*DateRates) Descriptor() ([]byte, []int) {
	return file_currency_currency_service_proto_rawDescGZIP(), []int{3}
}

func (x *DateRates) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *DateRates) GetRub() map[string]float64 {
	if x != nil {
		return x.Rub
	}
	return nil
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*DateRates           `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_currency_currency_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_currency_currency_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResponse) GetHistory() []*DateRates {
	if x != nil {
		return x.History
	}
	return nil
}

var File_currency_currency_service_proto protoreflect.FileDescriptor

const file_currency_currency_service_proto_rawDesc = "" +
	"\n" +
	"\x1fcurrency/currency_service.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x14GetRateByDateRequest\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\xb8\x01\n" +
	"\x15GetRateByDateResponse\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x127\n" +
	"\x03rub\x18\x02 \x03(\v2%.proto.GetRateByDateResponse.RubEntryR\x03rub\x1a6\n" +
	"\bRubEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"s\n" +
	"\x11GetHistoryRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xa0\x01\n" +
	"\tDateRates\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12+\n" +
	"\x03rub\x18\x02 \x03(\v2\x19.proto.DateRates.RubEntryR\x03rub\x1a6\n" +
	"\bRubEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"@\n" +
	"\x12GetHistoryResponse\x12*\n" +
	"\ahistory\x18\x01 \x03(\v2\x10.proto.DateRatesR\ahistory2\xa0\x01\n" +
	"\x0fCurrencyService\x12J\n" +
	"\rGetRateByDate\x12\x1b.proto.GetRateByDateRequest\x1a\x1c.proto.GetRateByDateResponse\x12A\n" +
	"\n" +
	"GetHistory\x12\x18.proto.GetHistoryRequest\x1a\x19.proto.GetHistoryResponseB5Z3github.com/lekss361/currencyservice/pkg/proto;protob\x06proto3"

var (
	file_currency_currency_service_proto_rawDescOnce sync.Once
	file_currency_currency_service_proto_rawDescData []byte
)

func file_currency_currency_service_proto_rawDescGZIP() []byte {
	file_currency_currency_service_proto_rawDescOnce.Do(func() {
		file_currency_currency_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_currency_service_proto_rawDesc), len(file_currency_currency_service_proto_rawDesc)))
	})
	return file_currency_currency_service_proto_rawDescData
}

var file_currency_currency_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_currency_currency_service_proto_goTypes = []any{
	(*GetRateByDateRequest)(nil),  // 0: proto.GetRateByDateRequest
	(*GetRateByDateResponse)(nil), // 1: proto.GetRateByDateResponse
	(*GetHistoryRequest)(nil),     // 2: proto.GetHistoryRequest
	(*DateRates)(nil),             // 3: proto.DateRates
	(*GetHistoryResponse)(nil),    // 4: proto.GetHistoryResponse
	nil,                           // 5: proto.GetRateByDateResponse.RubEntry
	nil,                           // 6: proto.DateRates.RubEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_currency_currency_service_proto_depIdxs = []int32{
	7,  // 0: proto.GetRateByDateRequest.date:type_name -> google.protobuf.Timestamp
	7,  // 1: proto.GetRateByDateResponse.date:type_name -> google.protobuf.Timestamp
	5,  // 2: proto.GetRateByDateResponse.rub:type_name -> proto.GetRateByDateResponse.RubEntry
	7,  // 3: proto.GetHistoryRequest.start:type_name -> google.protobuf.Timestamp
	7,  // 4: proto.GetHistoryRequest.end:type_name -> google.protobuf.Timestamp
	7,  // 5: proto.DateRates.date:type_name -> google.protobuf.Timestamp
	6,  // 6: proto.DateRates.rub:type_name -> proto.DateRates.RubEntry
	3,  // 7: proto.GetHistoryResponse.history:type_name -> proto.DateRates
	0,  // 8: proto.CurrencyService.GetRateByDate:input_type -> proto.GetRateByDateRequest
	2,  // 9: proto.CurrencyService.GetHistory:input_type -> proto.GetHistoryRequest
	1,  // 10: proto.CurrencyService.GetRateByDate:output_type -> proto.GetRateByDateResponse
	4,  // 11: proto.CurrencyService.GetHistory:output_type -> proto.GetHistoryResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_currency_currency_service_proto_init() }
func file_currency_currency_service_proto_init() {
	if File_currency_currency_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_currency_service_proto_rawDesc), len(file_currency_currency_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_currency_service_proto_goTypes,
		DependencyIndexes: file_currency_currency_service_proto_depIdxs,
		MessageInfos:      file_currency_currency_service_proto_msgTypes,
	}.Build()
	File_currency_currency_service_proto = out.File
	file_currency_currency_service_proto_goTypes = nil
	file_currency_currency_service_proto_depIdxs = nil
}
